eureka:
  client:
    register-with-eureka: false
spring:
  cloud:
    gateway:
      routes:
        - id: students
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/students/**
        - id: schools
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/schools/**
      discovery:
        locator:
          enabled: true
server:
  port: 8222
